/**
 * Standard IFD names for backplane instruments and publishers.
 */
export enum InstrumentBackplaneNames {
  Adc = 'Adc',
  Ahrs = 'Ahrs',
  AirspaceMonitor = 'AirspaceMonitor',
  Audio = 'Audio',
  Autopilot = 'Autopilot',
  Base = 'Base',
  CasAlertMonitors = 'CasAlertMonitors',
  CdiScaleManager = 'CdiScaleManager',
  Clock = 'Clock',
  DestinationPublisher = 'DestinationPublisher',
  Electrical = 'Electrical',
  FlightTimer = 'FlightTimer',
  FmsHooksManager = 'FmsHooksManager',
  FuelComputer = 'FuelComputer',
  FuelTotalizer = 'FuelTotalizer',
  FuelTotalizerPublisher = 'FuelTotalizerPublisher',
  Gnss = 'Gnss',
  IfdApproachManager = 'IfdApproachManager',
  IfdStartupManager = 'IfdStartupManager',
  IlluminationManager = 'IlluminationManager',
  MapData = 'MapData',
  NavCom = 'NavCom',
  NavEventsPublisher = 'NavEventsPublisher',
  TimerManager = 'TimerManager',
  Traffic = 'Traffic',
  VLocActivationManager = 'VLocActivationManager',
  VLocTuningManager = 'VLocTuningManager',
  VnavManager = 'VnavManager',
  Xpdr = 'Xpdr',
}
